version: "1"

services:
  database:
    build: ./database
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    networks:
      - myapp

  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - myapp

networks:
  myapp: