version: "1"

services:
  database:
    build: ./database
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    networks:
      - news_net

  backend:
    build: ./backend/BNews-master
    ports:
      - "8080:8080"
    restart: always
    networks:
      - news_net
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - news_net
    depends_on:
      - backend


networks:
  news_net: